using CSharpStart.Models;
namespace CSharpStart.Services;
public sealed class CourseService {
 public IReadOnlyList<Lesson> Lessons { get; } = [
 new(1,"はじめての出力","Console.WriteLine で言葉を表示します。","画面に「こんにちは、C#!」と表示する",["プログラムは、コンピュータへの指示書です。書いた順に上から実行されます。","C#で画面に文字を出すときは Console.WriteLine を使います。文字は必ず \" で囲みます。"],"Console.WriteLine(\"こんにちは\");","こんにちは","// ここに1行書きます\n","Console.WriteLine(\"こんにちは、C#!\");",["Console.WriteLine","こんにちは、C#!"],"Console.WriteLine(\"表示したい文字\"); と書きます。"),
 new(2,"変数に覚えさせる","値に名前を付け、あとで何度でも使います。","name を作り、名前を表示する",["変数は、値を覚えておくための名前付きの箱です。","string は文字を入れる箱の種類です。変数名だけを WriteLine に渡すと、中身を表示できます。"],"string name = \"さくら\";\nConsole.WriteLine(name);","さくら","string name = \"さくら\";\n// name を表示します\n","string name = \"さくら\";\nConsole.WriteLine(name);",["string name","Console.WriteLine(name)"],"string name = \"値\"; の形です。"),
 new(3,"計算してみよう","数値どうしは + や * で計算できます。","price と count の合計金額を表示する",["int は小数点のない数を入れる型です。数値は \" で囲みません。","掛け算は * です。計算式をそのまま WriteLine に入れることもできます。"],"int price = 120;\nint count = 3;\nConsole.WriteLine(price * count);","360","int price = 120;\nint count = 3;\n// 合計を表示します\n","int price = 120;\nint count = 3;\nConsole.WriteLine(price * count);",["int price","int count","Console.WriteLine(price * count)"],"掛け算には * を使います。"),
 new(4,"もし〜なら","if は条件が正しいときだけ処理を動かします。","score が60以上なら「合格」を表示する",["if は「もし条件が正しければ」という分かれ道です。","条件を丸カッコで囲み、動かす処理を { と } で囲みます。"],"int score = 80;\nif (score >= 60)\n{\n    Console.WriteLine(\"合格\");\n}","合格","int score = 80;\n// if 文を書きます\n","int score = 80;\nif (score >= 60)\n{\n    Console.WriteLine(\"合格\");\n}",["if","score >= 60","Console.WriteLine","合格"],"if (条件) の後を { } で囲みます。"),
 new(5,"繰り返して表示する","for は決まった回数だけ繰り返します。","0から2までの数を表示する",["同じ形の処理を何度も書く代わりに、for を使います。","i は回数を数えるための変数です。i++ は i を1増やすという意味です。"],"for (int i = 0; i < 3; i++)\n{\n    Console.WriteLine(i);\n}","0\n1\n2","// for 文を書きます\n","for (int i = 0; i < 3; i++)\n{\n    Console.WriteLine(i);\n}",["for","i < 3","Console.WriteLine(i)"],"for (int i = 0; i < 3; i++) の形を使います。")];
 public CheckResult Check(Lesson lesson,string code) { if(string.IsNullOrWhiteSpace(code)) return new(false,"まだコードが書かれていません。"+lesson.Hint); if(code.Count(c=>c=='{')!=code.Count(c=>c=='}')) return new(false,"{ と } の数がそろっているか確認しましょう。"); if(code.Count(c=>c=='\"')%2!=0) return new(false,"文字列を囲む \" が対になっているか確認しましょう。"); var missing=lesson.RequiredTokens.FirstOrDefault(x=>!code.Contains(x,StringComparison.Ordinal)); return missing is null?new(true,"合格です！ よくできました。次へ進みましょう。 "):new(false,"まだ合格ではありません。"+lesson.Hint); }
}
public sealed record CheckResult(bool Passed,string Message);
